<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "attach_file".
 *
 * @property integer $id
 * @property string $name
 * @property string $project_proposal_id
 *
 * @property \app\models\ProjectProposal $projectProposal
 * @property string $aliasModel
 */
abstract class AttachFile extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'attach_file';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'project_proposal_id'], 'required'],
            [['project_proposal_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['project_proposal_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ProjectProposal::className(), 'targetAttribute' => ['project_proposal_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'project_proposal_id' => Yii::t('models', 'Project Proposal ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjectProposal()
    {
        return $this->hasOne(\app\models\ProjectProposal::className(), ['id' => 'project_proposal_id']);
    }




}
