<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "employee_level".
 *
 * @property integer $id
 * @property integer $year
 * @property integer $phd_male_in
 * @property integer $phd_female_in
 * @property integer $phd_male_out
 * @property integer $phd_female_out
 * @property integer $master_male_in
 * @property integer $master_female_in
 * @property integer $master_male_out
 * @property integer $master_female_out
 * @property integer $bachelor_degree_male_in
 * @property integer $bachelor_degree_female_in
 * @property integer $bachelor_degree_male_out
 * @property integer $bachelor_degree_female_out
 * @property integer $bachelor_male_in
 * @property integer $bachelor_female_in
 * @property integer $bachelor_male_out
 * @property integer $bachelor_female_out
 * @property integer $middle_diploma_male_in
 * @property integer $middle_diploma_female_in
 * @property integer $middle_diploma_male_out
 * @property integer $middle_diploma_female_out
 * @property integer $lower_diploma_male_in
 * @property integer $lower_diploma_female_in
 * @property integer $lower_diploma_male_out
 * @property integer $lower_diploma_female_out
 * @property integer $ministry_id
 *
 * @property \app\models\Ministry $ministry
 * @property string $aliasModel
 */
abstract class EmployeeLevel extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'employee_level';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['year', 'phd_male_in', 'phd_female_in', 'phd_male_out', 'phd_female_out', 'master_male_in', 'master_female_in', 'master_male_out', 'master_female_out', 'bachelor_degree_male_in', 'bachelor_degree_female_in', 'bachelor_degree_male_out', 'bachelor_degree_female_out', 'bachelor_male_in', 'bachelor_female_in', 'bachelor_male_out', 'bachelor_female_out', 'middle_diploma_male_in', 'middle_diploma_female_in', 'middle_diploma_male_out', 'middle_diploma_female_out', 'lower_diploma_male_in', 'lower_diploma_female_in', 'lower_diploma_male_out', 'lower_diploma_female_out', 'ministry_id'], 'required'],
            [['year', 'phd_male_in', 'phd_female_in', 'phd_male_out', 'phd_female_out', 'master_male_in', 'master_female_in', 'master_male_out', 'master_female_out', 'bachelor_degree_male_in', 'bachelor_degree_female_in', 'bachelor_degree_male_out', 'bachelor_degree_female_out', 'bachelor_male_in', 'bachelor_female_in', 'bachelor_male_out', 'bachelor_female_out', 'middle_diploma_male_in', 'middle_diploma_female_in', 'middle_diploma_male_out', 'middle_diploma_female_out', 'lower_diploma_male_in', 'lower_diploma_female_in', 'lower_diploma_male_out', 'lower_diploma_female_out', 'ministry_id'], 'integer'],
            [['ministry_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Ministry::className(), 'targetAttribute' => ['ministry_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'year' => Yii::t('models', 'Year'),
            'phd_male_in' => Yii::t('models', 'Phd Male In'),
            'phd_female_in' => Yii::t('models', 'Phd Female In'),
            'phd_male_out' => Yii::t('models', 'Phd Male Out'),
            'phd_female_out' => Yii::t('models', 'Phd Female Out'),
            'master_male_in' => Yii::t('models', 'Master Male In'),
            'master_female_in' => Yii::t('models', 'Master Female In'),
            'master_male_out' => Yii::t('models', 'Master Male Out'),
            'master_female_out' => Yii::t('models', 'Master Female Out'),
            'bachelor_degree_male_in' => Yii::t('models', 'Bachelor Degree Male In'),
            'bachelor_degree_female_in' => Yii::t('models', 'Bachelor Degree Female In'),
            'bachelor_degree_male_out' => Yii::t('models', 'Bachelor Degree Male Out'),
            'bachelor_degree_female_out' => Yii::t('models', 'Bachelor Degree Female Out'),
            'bachelor_male_in' => Yii::t('models', 'Bachelor Male In'),
            'bachelor_female_in' => Yii::t('models', 'Bachelor Female In'),
            'bachelor_male_out' => Yii::t('models', 'Bachelor Male Out'),
            'bachelor_female_out' => Yii::t('models', 'Bachelor Female Out'),
            'middle_diploma_male_in' => Yii::t('models', 'Middle Diploma Male In'),
            'middle_diploma_female_in' => Yii::t('models', 'Middle Diploma Female In'),
            'middle_diploma_male_out' => Yii::t('models', 'Middle Diploma Male Out'),
            'middle_diploma_female_out' => Yii::t('models', 'Middle Diploma Female Out'),
            'lower_diploma_male_in' => Yii::t('models', 'Lower Diploma Male In'),
            'lower_diploma_female_in' => Yii::t('models', 'Lower Diploma Female In'),
            'lower_diploma_male_out' => Yii::t('models', 'Lower Diploma Male Out'),
            'lower_diploma_female_out' => Yii::t('models', 'Lower Diploma Female Out'),
            'ministry_id' => Yii::t('models', 'Ministry ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMinistry()
    {
        return $this->hasOne(\app\models\Ministry::className(), ['id' => 'ministry_id']);
    }




}
