<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "group_project_type".
 *
 * @property string $id
 * @property string $group_name
 * @property double $min_amount
 * @property double $max_amount
 * @property string $aliasModel
 */
abstract class GroupProjectType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'group_project_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['group_name', 'min_amount'], 'required'],
            [['min_amount', 'max_amount'], 'number'],
            [['group_name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'group_name' => Yii::t('models', 'Group Name'),
            'min_amount' => Yii::t('models', 'Min Amount'),
            'max_amount' => Yii::t('models', 'Max Amount'),
        ];
    }




}
