<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "loan".
 *
 * @property string $id
 * @property double $amount
 * @property double $interest_rate
 * @property string $project_id
 *
 * @property \app\models\Project $project
 * @property string $aliasModel
 */
abstract class Loan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'loan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['amount', 'interest_rate', 'project_id'], 'required'],
            [['amount', 'interest_rate'], 'number'],
            [['project_id'], 'integer'],
            [['project_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Project::className(), 'targetAttribute' => ['project_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'amount' => Yii::t('models', 'Amount'),
            'interest_rate' => Yii::t('models', 'Interest Rate'),
            'project_id' => Yii::t('models', 'Project ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProject()
    {
        return $this->hasOne(\app\models\Project::className(), ['id' => 'project_id']);
    }




}
