<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "project_progression".
 *
 * @property string $id
 * @property string $project_id
 * @property string $project_year
 * @property string $project_status_id
 * @property double $aproved_amount
 * @property double $proposal_amount
 * @property double $aproved_amount_oda
 *
 * @property \app\models\ProjectPayment[] $projectPayments
 * @property \app\models\Project $project
 * @property \app\models\ProjectStatus $projectStatus
 * @property string $aliasModel
 */
abstract class ProjectProgression extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'project_progression';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['project_id', 'project_year', 'project_status_id', 'proposal_amount'], 'required'],
            [['project_id', 'project_status_id'], 'integer'],
            [['project_year'], 'safe'],
            [['aproved_amount', 'proposal_amount', 'aproved_amount_oda'], 'number'],
            [['project_id', 'project_year'], 'unique', 'targetAttribute' => ['project_id', 'project_year']],
            [['project_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Project::className(), 'targetAttribute' => ['project_id' => 'id']],
            [['project_status_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ProjectStatus::className(), 'targetAttribute' => ['project_status_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'project_id' => Yii::t('models', 'Project ID'),
            'project_year' => Yii::t('models', 'Project Year'),
            'project_status_id' => Yii::t('models', 'Project Status ID'),
            'aproved_amount' => Yii::t('models', 'Aproved Amount'),
            'proposal_amount' => Yii::t('models', 'Proposal Amount'),
            'aproved_amount_oda' => Yii::t('models', 'Aproved Amount Oda'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjectPayments()
    {
        return $this->hasMany(\app\models\ProjectPayment::className(), ['project_progression_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProject()
    {
        return $this->hasOne(\app\models\Project::className(), ['id' => 'project_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjectStatus()
    {
        return $this->hasOne(\app\models\ProjectStatus::className(), ['id' => 'project_status_id']);
    }




}
