<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "project_payment".
 *
 * @property string $id
 * @property double $amount
 * @property string $payment_type
 * @property integer $is_oda
 * @property string $project_progression_id
 *
 * @property \app\models\ProjectProgression $projectProgression
 * @property string $aliasModel
 */
abstract class ProjectPayment extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const PAYMENT_TYPE_FIRST_SIX_MONTHS = 'first_six_months';
    const PAYMENT_TYPE_FULL_YEAR = 'full_year';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'project_payment';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['amount', 'payment_type', 'project_progression_id'], 'required'],
            [['amount'], 'number'],
            [['payment_type'], 'string'],
            [['is_oda', 'project_progression_id'], 'integer'],
            [['project_progression_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ProjectProgression::className(), 'targetAttribute' => ['project_progression_id' => 'id']],
            ['payment_type', 'in', 'range' => [
                    self::PAYMENT_TYPE_FIRST_SIX_MONTHS,
                    self::PAYMENT_TYPE_FULL_YEAR,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'amount' => Yii::t('models', 'Amount'),
            'payment_type' => Yii::t('models', 'Payment Type'),
            'is_oda' => Yii::t('models', 'Is Oda'),
            'project_progression_id' => Yii::t('models', 'Project Progression ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjectProgression()
    {
        return $this->hasOne(\app\models\ProjectProgression::className(), ['id' => 'project_progression_id']);
    }




    /**
     * get column payment_type enum value label
     * @param string $value
     * @return string
     */
    public static function getPaymentTypeValueLabel($value){
        $labels = self::optsPaymentType();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column payment_type ENUM value labels
     * @return array
     */
    public static function optsPaymentType()
    {
        return [
            self::PAYMENT_TYPE_FIRST_SIX_MONTHS => Yii::t('models', self::PAYMENT_TYPE_FIRST_SIX_MONTHS),
            self::PAYMENT_TYPE_FULL_YEAR => Yii::t('models', self::PAYMENT_TYPE_FULL_YEAR),
        ];
    }

}
