<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "project_proposal".
 *
 * @property string $id
 * @property string $project_name
 * @property string $start_year
 * @property string $end_year
 * @property string $amount
 * @property string $project_proposal_year_id
 * @property string $code_old_project
 *
 * @property \app\models\ProjectProposalYear $projectProposalYear
 * @property string $aliasModel
 */
abstract class ProjectProposal extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'project_proposal';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['project_name', 'start_year', 'end_year', 'amount', 'project_proposal_year_id'], 'required'],
            [['start_year', 'end_year'], 'safe'],
            [['amount', 'project_proposal_year_id'], 'integer'],
            [['project_name', 'code_old_project'], 'string', 'max' => 255],
            [['project_proposal_year_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ProjectProposalYear::className(), 'targetAttribute' => ['project_proposal_year_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'project_name' => Yii::t('models', 'Project Name'),
            'start_year' => Yii::t('models', 'Start Year'),
            'end_year' => Yii::t('models', 'End Year'),
            'amount' => Yii::t('models', 'Amount'),
            'project_proposal_year_id' => Yii::t('models', 'Project Proposal Year ID'),
            'code_old_project' => Yii::t('models', 'Code Old Project'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjectProposalYear()
    {
        return $this->hasOne(\app\models\ProjectProposalYear::className(), ['id' => 'project_proposal_year_id']);
    }




}
